# Generated by Django 4.2.2 on 2023-07-10 04:57

from django.db import migrations, models
import live.models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_iphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='vivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to=live.models.getFileName)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('quantity', models.IntegerField()),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
